import { Chore, Section } from '../types/chores';
import { getTodayStr, computeNextDate } from '../utils/dateUtils';

export const TODAY = getTodayStr();
const TOMORROW = (() => { const d = new Date(); d.setDate(d.getDate() + 1); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })();
const YESTERDAY = (() => { const d = new Date(); d.setDate(d.getDate() - 1); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })();
const daysAgo = (n: number) => { const d = new Date(); d.setDate(d.getDate() - n); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };

export const INITIAL_SECTIONS: Section[] = [
  { id: 's1', title: 'Morning Routine', themeColor: '#F59E0B', date: TODAY, priorityIndex: 0, isCollapsed: false },
  { id: 's2', title: 'Kitchen', themeColor: '#10B981', date: TODAY, priorityIndex: 1, isCollapsed: false },
  { id: 's3', title: 'Outdoor', themeColor: '#3B82F6', date: TODAY, priorityIndex: 2, isCollapsed: false },
  { id: 's4', title: 'Maintenance', themeColor: '#6366F1', date: TODAY, priorityIndex: 3, isCollapsed: false },
];

export const INITIAL_CHORES: Chore[] = [
  // SC-1: Simple unassigned
  { id: 'v1', title: 'Empty Kitchen Trash', assignee: null, avatar: '👤', pool: 'Me', points: 15, estMinutes: 5, dueDate: TODAY, due: TODAY, status: 'pending', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  // SC-2: Assigned to Alex (me)
  { id: 'v2', title: 'Wipe Counters', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 20, estMinutes: 10, dueDate: TODAY, due: TODAY, status: 'pending', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 1, sectionId: 's2', isOverdue: false },
  // SC-3: Assigned to Dad (other person)
  { id: 'v3', title: 'Water Front Plants', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 25, estMinutes: 15, dueDate: TODAY, due: TODAY, status: 'pending', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  // SC-4: Photo required — before & after
  { id: 'v4', title: 'Clean Microwave', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 50, estMinutes: 20, dueDate: TODAY, due: TODAY, status: 'pending', photoRequired: true, photoMode: 'both', photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 2, sectionId: 's2', isOverdue: false },
  // SC-5: Photo required — after only, assigned to Dad
  { id: 'v5', title: 'Wash Car', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 100, estMinutes: 45, dueDate: TODAY, due: TODAY, status: 'pending', photoRequired: true, photoMode: 'after', photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 1, sectionId: 's3', isOverdue: false },
  // SC-6: Recurring daily (Alex) — with recurringGroupId
  { id: 'v6', title: 'Daily Vitamin', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: TODAY, due: TODAY, status: 'pending', isRecurring: true, recurrenceRule: 'Every Day', recurringGroupId: 'rg_daily_vitamin', seriesStartDate: TODAY, nextRecurringDate: computeNextDate(TODAY, 'Every Day', 1), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false, recurringSection: { title: 'Morning Routine', color: '#F59E0B' } },
  // SC-7: Recurring every 3 days (Lily) — custom FREQ=Daily;INTERVAL=3, with recurringGroupId — tests HAR-72 dot fix
  { id: 'v7', title: 'Water Houseplants', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 15, estMinutes: 10, dueDate: TODAY, due: TODAY, status: 'pending', isRecurring: true, recurrenceRule: 'FREQ=Daily;INTERVAL=3', recurringGroupId: 'rg_water_plants', seriesStartDate: TODAY, nextRecurringDate: computeNextDate(TODAY, 'FREQ=Daily;INTERVAL=3', 1), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 1, sectionId: 's3', isOverdue: false },
  // SC-8: Recurring weekly (Dad) — photo required, with recurringGroupId
  { id: 'v8', title: 'Mow Lawn', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 150, estMinutes: 60, dueDate: TODAY, due: TODAY, status: 'pending', isRecurring: true, recurrenceRule: 'Every Week', recurringGroupId: 'rg_mow_lawn', seriesStartDate: TODAY, nextRecurringDate: computeNextDate(TODAY, 'Every Week', 1), photoRequired: true, photoMode: 'after', photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 2, sectionId: 's3', isOverdue: false },
  // SC-9: Recurring monthly (Alex) — ON THE first Monday, with recurringGroupId
  { id: 'v9', title: 'Budget Review', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 30, estMinutes: 20, dueDate: TODAY, due: TODAY, status: 'pending', isRecurring: true, recurrenceRule: 'FREQ=Monthly;INTERVAL=1;BYSETPOS=1;BYDAY=Mon', recurringGroupId: 'rg_budget_review', seriesStartDate: TODAY, nextRecurringDate: computeNextDate(TODAY, 'FREQ=Monthly;INTERVAL=1;BYSETPOS=1;BYDAY=Mon', 1), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 3, sectionId: null, isOverdue: false },
  // SC-10: Recurring yearly (Mom) — with recurringGroupId
  { id: 'v10', title: 'Annual AC Filter Replace', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 50, estMinutes: 15, dueDate: TODAY, due: TODAY, status: 'pending', isRecurring: true, recurrenceRule: 'Every Year', recurringGroupId: 'rg_ac_filter', seriesStartDate: TODAY, nextRecurringDate: computeNextDate(TODAY, 'Every Year', 1), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's4', isOverdue: false },
  // SC-11: Overdue simple — Alex, 3 days ago — tests delete+undo overdue restore
  { id: 'v11', title: 'Clean Stovetop', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 40, estMinutes: 20, dueDate: daysAgo(3), due: daysAgo(3), status: 'pending', isOverdue: true, overdueDays: 3, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2' },
  // SC-12: Overdue simple — Dad, 7 days ago
  { id: 'v12', title: 'Fix Leaky Faucet', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 75, estMinutes: 30, dueDate: daysAgo(7), due: daysAgo(7), status: 'pending', isOverdue: true, overdueDays: 7, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: true, priorityIndex: 1, sectionId: 's4' },
  // SC-13: Overdue recurring — Lily, 5 days ago, missedStreak=2 — tests missedStreak badge + HAR-118 Go To
  { id: 'v13', title: 'Morning Stretch', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 20, estMinutes: 10, dueDate: daysAgo(5), due: daysAgo(5), status: 'pending', isRecurring: true, recurrenceRule: 'Every Day', recurringGroupId: 'rg_morning_stretch', seriesStartDate: daysAgo(12), isOverdue: true, overdueDays: 5, missedStreak: 5, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 2, sectionId: 's1' },
  // SC-13b: Overdue recurring — Alex, weekly — HAR-118 Go To test (weekly)
  { id: 'v13b', title: 'Bedroom Tidy', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 25, estMinutes: 15, dueDate: daysAgo(8), due: daysAgo(8), status: 'pending', isRecurring: true, recurrenceRule: 'Every Week', recurringGroupId: 'rg_bedroom_tidy', seriesStartDate: daysAgo(22), isOverdue: true, overdueDays: 8, missedStreak: 2, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 3, sectionId: 's1' },
  // SC-13c: Overdue recurring — Dad, bi-weekly — HAR-118 Go To test (every 2 weeks)
  { id: 'v13c', title: 'Vacuum All Floors', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 40, estMinutes: 30, dueDate: daysAgo(16), due: daysAgo(16), status: 'pending', isRecurring: true, recurrenceRule: 'Every 2 Weeks', recurringGroupId: 'rg_vacuum_floors', seriesStartDate: daysAgo(30), isOverdue: true, overdueDays: 16, missedStreak: 2, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 4, sectionId: 's3' },
  // SC-14: wasOverdue recovery — moved to today — tests overdue badge on chore card
  { id: 'v14', title: 'Rake Leaves', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 60, estMinutes: 30, dueDate: TODAY, due: TODAY, status: 'pending', isOverdue: false, wasOverdue: true, overdueDays: 4, isOverdueRecovery: true, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 1, sectionId: 's3' },
  // SC-15: Future chore (tomorrow)
  { id: 'v15', title: 'Take Out Recycling', assignee: null, avatar: '👤', pool: 'Me', points: 30, estMinutes: 10, dueDate: TOMORROW, due: TOMORROW, status: 'pending', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  // SC-16: Completed by self (Alex)
  { id: 'v16', title: 'Feed the Dog', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 15, estMinutes: 5, dueDate: TODAY, due: TODAY, status: 'completed', completedBy: 'Leo Kim', completedAt: TODAY + 'T08:00:00Z', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 2, sectionId: 's1', isOverdue: false },
  // SC-17: Completed by other (Mom completed Dad's chore)
  { id: 'v17', title: 'Take Out Trash', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 20, estMinutes: 5, dueDate: TODAY, due: TODAY, status: 'completed', completedBy: 'Sarah Kim', completedAt: TODAY + 'T09:00:00Z', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 4, sectionId: 's2', isOverdue: false },
  // SC-18: Uncategorized (no section)
  { id: 'v18', title: 'Check Mail', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 5, estMinutes: 5, dueDate: TODAY, due: TODAY, status: 'pending', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: null, isOverdue: false },
  // SC-19: Completed with photo proof
  { id: 'v19', title: 'Deep Clean Oven', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 500, estMinutes: 120, dueDate: TODAY, due: TODAY, status: 'completed', completedBy: 'Sarah Kim', completedAt: TODAY + 'T10:00:00Z', photoRequired: true, photoMode: 'both', photoProvided: { before: true, beforeUri: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400', after: true, afterUri: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=400' }, isNudged: false, priorityIndex: 3, sectionId: 's2', isOverdue: false },
  // SC-20: Overdue unassigned — 14 days — tests unassigned skip on bulk complete
  { id: 'v20', title: 'Replace Air Filter', assignee: null, avatar: '👤', pool: 'Me', points: 50, estMinutes: 15, dueDate: daysAgo(14), due: daysAgo(14), status: 'pending', isOverdue: true, overdueDays: 14, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: true, priorityIndex: 3, sectionId: 's4' },

  // HAR-36: Historical completed chores for analytics (10+ per member) — dueDate matches completedAt date
  // --- Alex history ---
  { id: 'h-alex-1', title: 'Daily Vitamin', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: daysAgo(1), due: daysAgo(1), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 1 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-alex-2', title: 'Feed the Dog', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 15, estMinutes: 5, dueDate: daysAgo(2), due: daysAgo(2), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 2 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-alex-3', title: 'Wipe Counters', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 20, estMinutes: 10, dueDate: daysAgo(3), due: daysAgo(3), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 3 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-alex-4', title: 'Daily Vitamin', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: daysAgo(4), due: daysAgo(4), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 4 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-alex-5', title: 'Check Mail', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 5, estMinutes: 5, dueDate: daysAgo(5), due: daysAgo(5), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 5 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: null, isOverdue: false },
  { id: 'h-alex-6', title: 'Daily Vitamin', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: daysAgo(6), due: daysAgo(6), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 6 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-alex-7', title: 'Wipe Counters', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 20, estMinutes: 10, dueDate: daysAgo(8), due: daysAgo(8), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 8 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-alex-8', title: 'Feed the Dog', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 15, estMinutes: 5, dueDate: daysAgo(10), due: daysAgo(10), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 10 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-alex-9', title: 'Daily Vitamin', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: daysAgo(11), due: daysAgo(11), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 11 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-alex-10', title: 'Check Mail', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 5, estMinutes: 5, dueDate: daysAgo(14), due: daysAgo(14), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 14 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: null, isOverdue: false },
  { id: 'h-alex-11', title: 'Empty Kitchen Trash', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 15, estMinutes: 5, dueDate: daysAgo(16), due: daysAgo(16), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 16 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },

  // --- Mom history ---
  { id: 'h-mom-1', title: 'Deep Clean Oven', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 500, estMinutes: 120, dueDate: daysAgo(1), due: daysAgo(1), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 1 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-mom-2', title: 'Wipe Counters', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 20, estMinutes: 10, dueDate: daysAgo(2), due: daysAgo(2), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 2 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-mom-3', title: 'Clean Microwave', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 50, estMinutes: 20, dueDate: daysAgo(3), due: daysAgo(3), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 3 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-mom-4', title: 'Deep Clean Oven', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 500, estMinutes: 120, dueDate: daysAgo(7), due: daysAgo(7), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 7 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-mom-5', title: 'Empty Kitchen Trash', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 15, estMinutes: 5, dueDate: daysAgo(8), due: daysAgo(8), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 8 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-mom-6', title: 'Wipe Counters', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 20, estMinutes: 10, dueDate: daysAgo(9), due: daysAgo(9), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 9 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-mom-7', title: 'Clean Microwave', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 50, estMinutes: 20, dueDate: daysAgo(12), due: daysAgo(12), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 12 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-mom-8', title: 'Check Mail', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 5, estMinutes: 5, dueDate: daysAgo(15), due: daysAgo(15), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 15 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: null, isOverdue: false },
  { id: 'h-mom-9', title: 'Empty Kitchen Trash', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 15, estMinutes: 5, dueDate: daysAgo(18), due: daysAgo(18), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 18 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-mom-10', title: 'Deep Clean Oven', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 500, estMinutes: 120, dueDate: daysAgo(21), due: daysAgo(21), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 21 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },

  // --- Dad history ---
  { id: 'h-dad-1', title: 'Mow Lawn', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 150, estMinutes: 60, dueDate: daysAgo(2), due: daysAgo(2), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 2 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'h-dad-2', title: 'Water Front Plants', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 25, estMinutes: 15, dueDate: daysAgo(3), due: daysAgo(3), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 3 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'h-dad-3', title: 'Wash Car', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 100, estMinutes: 45, dueDate: daysAgo(5), due: daysAgo(5), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 5 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'h-dad-4', title: 'Mow Lawn', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 150, estMinutes: 60, dueDate: daysAgo(9), due: daysAgo(9), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 9 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'h-dad-5', title: 'Water Front Plants', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 25, estMinutes: 15, dueDate: daysAgo(10), due: daysAgo(10), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 10 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'h-dad-6', title: 'Fix Leaky Faucet', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 75, estMinutes: 30, dueDate: daysAgo(12), due: daysAgo(12), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 12 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's4', isOverdue: false },
  { id: 'h-dad-7', title: 'Wash Car', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 100, estMinutes: 45, dueDate: daysAgo(14), due: daysAgo(14), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 14 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'h-dad-8', title: 'Mow Lawn', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 150, estMinutes: 60, dueDate: daysAgo(16), due: daysAgo(16), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 16 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'h-dad-9', title: 'Water Front Plants', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 25, estMinutes: 15, dueDate: daysAgo(20), due: daysAgo(20), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 20 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'h-dad-10', title: 'Fix Leaky Faucet', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 75, estMinutes: 30, dueDate: daysAgo(25), due: daysAgo(25), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 25 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's4', isOverdue: false },

  // --- Lily history ---
  { id: 'h-lily-1', title: 'Check Mail', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 5, estMinutes: 5, dueDate: daysAgo(1), due: daysAgo(1), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 1 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: null, isOverdue: false },
  { id: 'h-lily-2', title: 'Daily Vitamin', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: daysAgo(2), due: daysAgo(2), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 2 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-lily-3', title: 'Wipe Counters', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 20, estMinutes: 10, dueDate: daysAgo(4), due: daysAgo(4), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 4 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-lily-4', title: 'Check Mail', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 5, estMinutes: 5, dueDate: daysAgo(5), due: daysAgo(5), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 5 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: null, isOverdue: false },
  { id: 'h-lily-5', title: 'Empty Kitchen Trash', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 15, estMinutes: 5, dueDate: daysAgo(7), due: daysAgo(7), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 7 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-lily-6', title: 'Daily Vitamin', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: daysAgo(9), due: daysAgo(9), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 9 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-lily-7', title: 'Wipe Counters', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 20, estMinutes: 10, dueDate: daysAgo(11), due: daysAgo(11), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 11 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-lily-8', title: 'Check Mail', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 5, estMinutes: 5, dueDate: daysAgo(13), due: daysAgo(13), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 13 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: null, isOverdue: false },
  { id: 'h-lily-9', title: 'Empty Kitchen Trash', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 15, estMinutes: 5, dueDate: daysAgo(17), due: daysAgo(17), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 17 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'h-lily-10', title: 'Daily Vitamin', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: daysAgo(22), due: daysAgo(22), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 22 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false },
  { id: 'h-lily-11', title: 'Water Front Plants', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 25, estMinutes: 15, dueDate: daysAgo(27), due: daysAgo(27), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 27 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  // ── LAST WEEK SCENARIO (planned 8, completed 5, missed 3) ──────────────────
  { id: 'lw-1', title: 'Vacuum Living Room', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 30, estMinutes: 20, dueDate: daysAgo(8), due: daysAgo(8), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 8 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'lw-2', title: 'Do Laundry', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 40, estMinutes: 30, dueDate: daysAgo(9), due: daysAgo(9), status: 'completed', completedBy: 'Sarah Kim', completedAt: new Date(Date.now() - 9 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'lw-3', title: 'Sweep Floors', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 20, estMinutes: 15, dueDate: daysAgo(10), due: daysAgo(10), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 10 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'lw-4', title: 'Clean Bathroom', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 35, estMinutes: 25, dueDate: daysAgo(11), due: daysAgo(11), status: 'completed', completedBy: 'Leo Kim', completedAt: new Date(Date.now() - 11 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  { id: 'lw-5', title: 'Mop Kitchen', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 25, estMinutes: 20, dueDate: daysAgo(12), due: daysAgo(12), status: 'completed', completedBy: 'Haewon Kim', completedAt: new Date(Date.now() - 12 * 86400000).toISOString(), photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's2', isOverdue: false },
  // missed last week (still pending, not deleted, dueDate in last week)
  { id: 'lw-6', title: 'Wash Windows', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 45, estMinutes: 40, dueDate: daysAgo(9), due: daysAgo(9), status: 'pending', isOverdue: true, overdueDays: 9, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 1, sectionId: 's4' },
  { id: 'lw-7', title: 'Organize Garage', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 80, estMinutes: 60, dueDate: daysAgo(11), due: daysAgo(11), status: 'pending', isOverdue: true, overdueDays: 11, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: true, priorityIndex: 2, sectionId: 's4' },
  { id: 'lw-8', title: 'Water Back Garden', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 20, estMinutes: 15, dueDate: daysAgo(10), due: daysAgo(10), status: 'pending', isOverdue: true, overdueDays: 10, photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 3, sectionId: 's3' },
  // ── NEXT WEEK SCENARIO (6 upcoming: 4 recurring + 2 one-off) ──────────────
  { id: 'nw-1', title: 'Weekly Lawn Mow', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 150, estMinutes: 60, dueDate: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 1)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), due: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 1)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), status: 'pending', isRecurring: true, recurrenceRule: 'Every Week', recurringGroupId: 'rg_nw_lawn', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 0, sectionId: 's3', isOverdue: false },
  { id: 'nw-2', title: 'Take Out Recycling', assignee: 'Sarah Kim', avatar: '👩🏼', pool: 'Parents', points: 20, estMinutes: 10, dueDate: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 2)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), due: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 2)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), status: 'pending', isRecurring: true, recurrenceRule: 'Every Week', recurringGroupId: 'rg_nw_recycling', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 1, sectionId: 's2', isOverdue: false },
  { id: 'nw-3', title: 'Daily Vitamin (Alex)', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 10, estMinutes: 2, dueDate: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 1)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), due: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 1)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), status: 'pending', isRecurring: true, recurrenceRule: 'Every Day', recurringGroupId: 'rg_daily_vitamin', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 2, sectionId: 's1', isOverdue: false },
  { id: 'nw-4', title: 'Water Houseplants', assignee: 'Leo Kim', avatar: '👧🏻', pool: 'Kids', points: 15, estMinutes: 10, dueDate: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 3)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), due: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 3)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), status: 'pending', isRecurring: true, recurrenceRule: 'FREQ=Daily;INTERVAL=3', recurringGroupId: 'rg_water_plants', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 3, sectionId: 's3', isOverdue: false },
  { id: 'nw-5', title: 'Fix Porch Light', assignee: 'Haewon Kim', avatar: '👨🏻', pool: 'Parents', points: 50, estMinutes: 20, dueDate: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 2)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), due: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 2)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), status: 'pending', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 4, sectionId: 's4', isOverdue: false },
  { id: 'nw-6', title: 'Sort Recycling', assignee: 'Leo Kim', avatar: '👦🏻', pool: 'Kids', points: 20, estMinutes: 15, dueDate: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 4)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), due: (() => { const d = new Date(); d.setDate(d.getDate() + (7 - d.getDay() + 4)); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; })(), status: 'pending', photoRequired: false, photoProvided: { before: false, after: false }, isNudged: false, priorityIndex: 5, sectionId: 's2', isOverdue: false },
  // 52-week heatmap dummy data — realistic chore history
  ...(() => {
    const members = [
      { name: 'Dad', avatar: '👨🏻', pool: 'Parents' },
      { name: 'Mom', avatar: '👩🏼', pool: 'Parents' },
      { name: 'Alex', avatar: '👦🏻', pool: 'Kids' },
      { name: 'Lily', avatar: '👧🏻', pool: 'Kids' },
    ];
    const titles = ['Vacuum Living Room', 'Wash Dishes', 'Take Out Trash', 'Wipe Counters', 'Feed the Dog', 'Do Laundry', 'Sweep Floors', 'Water Plants', 'Clean Bathroom', 'Mop Kitchen', 'Empty Dishwasher', 'Check Mail', 'Daily Vitamin', 'Fold Laundry'];
    const result: any[] = [];
    let idxCounter = 0;
    for (let weekAgo = 52; weekAgo >= 3; weekAgo--) {
      // activity ramps up closer to present (2-6 chores/week)
      const count = weekAgo > 40 ? 2 : weekAgo > 20 ? 3 : weekAgo > 10 ? 4 : 5;
      for (let i = 0; i < count; i++) {
        const daysBack = weekAgo * 7 - Math.floor(Math.random() * 7);
        const m = members[idxCounter % members.length];
        const title = titles[idxCounter % titles.length];
        idxCounter++;
        const completedDate = new Date(Date.now() - daysBack * 86400000);
        const completedDateStr = `${completedDate.getFullYear()}-${String(completedDate.getMonth()+1).padStart(2,'0')}-${String(completedDate.getDate()).padStart(2,'0')}`;
        result.push({
          id: `hmap-${weekAgo}-${i}`,
          title,
          assignee: m.name, avatar: m.avatar, pool: m.pool,
          points: 10 + (idxCounter % 4) * 10,
          estMinutes: 10, dueDate: completedDateStr, due: completedDateStr,
          status: 'completed' as const,
          completedBy: m.name,
          completedAt: completedDate.toISOString(),
          photoRequired: false, photoProvided: { before: false, after: false },
          isNudged: false, priorityIndex: 0, sectionId: 's1', isOverdue: false,
        });
      }
    }
    return result;
  })(),
];

export const FAMILY_MEMBERS = [
  { name: 'Dad', avatar: '👨🏻', role: 'Parent', pool: 'Parents', stats: { choresCompleted: 42, pointsEarned: 1250, streak: 5 } },
  { name: 'Mom', avatar: '👩🏼', role: 'Parent', pool: 'Parents', stats: { choresCompleted: 38, pointsEarned: 1100, streak: 3 } },
  { name: 'Alex', avatar: '👦🏻', role: 'Child', pool: 'Kids', stats: { choresCompleted: 25, pointsEarned: 850, streak: 7 } },
  { name: 'Lily', avatar: '👧🏻', role: 'Child', pool: 'Kids', stats: { choresCompleted: 18, pointsEarned: 600, streak: 4 } },
];

export const SECTION_COLORS = ['#FF453A', '#FF9F0A', '#FFD60A', '#32D74B', '#0A84FF', '#BF5AF2', '#1C1C1E'];
export const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
export const RECURRING_FREQUENCIES = ['Daily', 'Weekly', 'Monthly', 'Yearly'];
export const RECURRING_PRESETS = ['Every Day', 'Every Week', 'Every Month', 'Every Year'];
export const DAYS_OF_WEEK = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
export const WEEK_ORDINALS = ['First', 'Second', 'Third', 'Fourth', 'Last'];
